version: "2.4"

services:
  icecast:
    container_name: icecast
    image: lyr7d1h/icecast:latest
    restart: unless-stopped
    environment:
      - ICECAST_SOURCE_PASSWORD=mopidy
      - ICECAST_ADMIN_PASSWORD=mopidy
      - ICECAST_PASSWORD=mopidy
      - ICECAST_RELAY_PASSWORD=mopidy
    ports:
      - 8000:8000

  mopidy:
    container_name: mopidy
    image: lyr7d1h/mopidy:latest
    restart: unless-stopped
    command: --config /mopidy/mopidy.conf
    ports:
      - 6600:6600
      - 6680:6680
    depends_on:
      - icecast
    volumes:
      - ./mopidy.conf:/mopidy/mopidy.conf
      - ./mopidy-icecast/:/mopidy