version: "3"

services:

  mopidy-icecast:
    build:
      context: mopidy/
    restart: always
    command: mopidy
    ports:
     - 6601:6600
     - 6681:6680
    depends_on:
      - icecast
    volumes:
      - ~/mopidy-icesnap/mopidy-icecast.conf:/mopidy_default.conf
      - ~/mopidy-icecast-data/:/mopidy

  icecast:
    build:
      context: icecast/
    restart: always
    environment:
      - ICECAST_SOURCE_PASSWORD=mopidy
      - ICECAST_ADMIN_PASSWORD=mopidy
      - ICECAST_PASSWORD=mopidy
      - ICECAST_RELAY_PASSWORD=mopidy
    ports:
    - 8001:8000