version: "3"

services:

  mopidy-snapserver:
    build:
      context: ../mopidy/
    restart: always
    command: mopidy
    ports:
      - 6600:6600
      - 6680:6680
    depends_on:
      - snapserver
    volumes:
      - ~/mopidy-icesnap/mopidy-snapserver.conf:/mopidy_default.conf
      - ~/mopidy-snapserver-data/:/mopidy

  snapserver:
    build:
      context: .
    restart: always
    command: snapserver
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780
      - 4953:4953