name: stream-manager

on: 
  workflow_dispatch:
  push:
    paths:
    - 'stream-manager/**'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      -
        name: Build
        run: |
          cd stream-manager
          docker build . # will run buildx
