version: "3"

services:

  snapserver:
    container_name: snapserver
    build:
      context: ../snapserver/
      args:
        SPOTIFY_USERNAME: <SPOTIFY_USERNAME>
        SPOTIFY_PASSWORD: <SPOTIFY_PASSWORD>
    restart: always
    command: snapserver
    network_mode: "host"
    volumes:
      - /tmp:/tmp

  mopidy-snapserver:
    container_name: mopidy-snapserver
    build:
      context: ../mopidy/
    restart: always
    command: mopidy
    ports:
      - 6600:6600
      - 6680:6680
    depends_on:
      - snapserver
    volumes:
      - ~/mopidy-icesnap/mopidy/mopidy-snapserver.conf:/mopidy_default.conf
      - ~/mopidy-snapserver-data/:/mopidy
      - /tmp:/tmp

  stream-manager:
    container_name: stream-manager
    build:
      context: ../stream-manager/
      args:
        SNAPSERVER: <SNAPSERVER_IP>
    restart: always
    depends_on:
      - snapserver