version: "3"

services:
  snapserver:
    container_name: snapserver
    build:
      context: ../snapserver/
    restart: unless-stopped
    command: snapserver
    network_mode: "host"
    volumes:
      - ~/snapserver/:/root/.config/snapserver/
      - ~/snapserver/snapserver.conf:/etc/snapserver.conf
      - /tmp:/tmp

  mopidy-snapserver:
    container_name: mopidy-snapserver
    build:
      context: ../mopidy/
    restart: unless-stopped
    command: mopidy
    ports:
      - 6600:6600
      - 6680:6680
    depends_on:
      - snapserver
    volumes:
      - ~/mopidy-icesnap/mopidy/mopidy-snapserver.conf:/mopidy_default.conf
      - ~/mopidy-snapserver-data/:/mopidy
      - /tmp:/tmp

  stream-manager:
    container_name: stream-manager
    build:
      context: ../stream-manager/
    environment:
      -  SNAPSERVER_IP=<SNAPSERVER_IP>
      -  SNAPSERVER_PORT=<SNAPSERVER_PORT>
    restart: unless-stopped
    depends_on:
      - snapserver